# play for nginx role

- name: Ensure host is part of docker
  ansible.builtin.assert:
    that:
      - docker
    msg: "'nginx' requires 'docker'"

- name: Create network for proxying
  community.docker.docker_network:
    name: "{{ proxy_net }}"
    driver_options:
      com.docker.network.bridge.name: "{{ proxy_net }}"
  become: yes

- name: Create nginx directories
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/nginx/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - conf.d
    - vhost.d
    - html
    - certs
    - templates

- name: Download nginx.tmpl
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nginx-proxy/nginx-proxy/master/nginx.tmpl
    dest: /home/{{ ansible_user }}/nginx/templates/nginx.tmpl

- name: Create the nginx-proxy certs volume
  docker_volume:
    name: nginx-proxy-certs
  become: yes

- name: Create the nginx-proxy conf volume
  docker_volume:
    name: nginx-proxy-conf
  become: yes

- name: Create the nginx-proxy html volume
  docker_volume:
    name: nginx-proxy-html
  become: yes

- name: Create the nginx-proxy vhost volume
  docker_volume:
    name: nginx-proxy-vhost
  become: yes

- name: Create the nginx-proxy acme volume
  docker_volume:
    name: nginx-proxy-acme
  become: yes

- name: Start nginx container
  community.docker.docker_container:
    image: "nginx"
    name: "nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "nginx-proxy-conf:/etc/nginx/conf.d"
      - "nginx-proxy-vhost:/etc/nginx/vhost.d"
      - "nginx-proxy-html:/usr/share/nginx/html"
      - "nginx-proxy-certs:/etc/nginx/certs:ro"
    restart_policy: "always"
    networks:
      - name: "{{ proxy_net }}"
  become: yes

- name: Start docker-gen container
  community.docker.docker_container:
    image: "jwilder/docker-gen"
    name: "nginx-proxy-gen"
    volumes:
      - "nginx-proxy-conf:/etc/nginx/conf.d"
      - "nginx-proxy-vhost:/etc/nginx/vhost.d"
      - "nginx-proxy-html:/usr/share/nginx/html"
      - "nginx-proxy-certs:/etc/nginx/certs:ro"
      - "/home/{{ ansible_user }}/nginx/templates:/etc/docker-gen/templates"
      - "/var/run/docker.sock:/tmp/docker.sock:ro,Z"
    restart_policy: "always"
    networks:
      - name: "{{ proxy_net }}"
    privileged: yes
    security_opts:
      - "label=disable"
    command: "/etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
  become: yes

- name: Start ACME container
  community.docker.docker_container:
    image: "nginxproxy/acme-companion"
    name: "nginx-proxy-acme"
    volumes:
      - "nginx-proxy-conf:/etc/nginx/conf.d"
      - "nginx-proxy-vhost:/etc/nginx/vhost.d"
      - "nginx-proxy-html:/usr/share/nginx/html"
      - "nginx-proxy-certs:/etc/nginx/certs:rw"
      - "nginx-proxy-acme:/etc/acme.sh"
      - "/var/run/docker.sock:/var/run/docker.sock:ro,Z"
    env:
      NGINX_PROXY_CONTAINER: "nginx"
      NGINX_DOCKER_GEN_CONTAINER: "nginx-proxy-gen"
      DEFAULT_EMAIL: "joao.p.l.borges@tecnico.ulisboa.pt"
    restart_policy: "always"
    networks:
      - name: "{{ proxy_net }}"
    privileged: yes
    security_opts:
      - "label=disable"
  become: yes
