- hosts: docker
  become_method: sudo
  roles:
    - docker

- hosts: caddy
  become_method: sudo
  roles:
    - caddy

- hosts: focalboard
  become_method: sudo
  roles:
    - focalboard

- hosts: portainer
  become_method: sudo
  roles:
    - portainer

- hosts: gotify
  become_method: sudo
  roles:
    - gotify

- hosts: diun
  become_method: sudo
  roles:
    - diun

- hosts: wallabag
  become_method: sudo
  roles:
    - wallabag

- hosts: bot
  become_method: sudo
  vars_prompt:
    - name: registry_password
      prompt: "registry login token"
      private: yes
    - name: discord_token
      prompt: "discord bot token"
      private: yes
  roles:
    - bot
