# play for focalboard role

- name: Ensure host is part of caddy and docker
  ansible.builtin.assert:
    that:
      - docker
      - caddy
    msg: "'focalboard' requires 'docker' and 'caddy'"
  tags:
    - always

- name: Create focalboard directories
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/focalboard/data
    state: directory
    owner: nobody
    group: nobody
  become: yes
  tags:
    - setup

- name: Download focalboard server_config.json
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/mattermost/focalboard/main/docker/server_config.json
    dest: /home/{{ ansible_user }}/focalboard/server_config.json
  tags:
    - setup

- name: Start focalboard container
  community.docker.docker_container:
    image: mattermost/focalboard:0.11.0
    name: focalboard
    restart_policy: unless-stopped
    volumes:
      - /home/{{ ansible_user }}/focalboard/server_config.json/:/opt/focalboard/config.json:ro,Z
      - /home/{{ ansible_user }}/focalboard/data/:/data/
    network_mode: bridge
    networks:
      - name: "{{ proxy_net }}"
    security_opts:
      - "label=disable"
    pull: yes
  become: yes
  tags:
    - run

- name: Copy focalboard Caddyfile
  ansible.builtin.template:
    src: focalboard-caddyfile.j2
    dest: /home/{{ ansible_user }}/caddy/config/conf.d/focalboard.caddyfile
  tags:
    - run
  notify:
    caddy reload

- import_tasks: backups.yml
