# play for caddy role

- name: Ensure host is part of docker
  ansible.builtin.assert:
    that:
      - docker
    msg: "'caddy' requires 'docker'"
  tags:
    - always

- name: Create caddy directories
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/caddy/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - data
    - config/conf.d
    - config/logs
  tags:
    - setup

- name: Create caddy log file
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/caddy/config/logs/access.log"
    state: file
    mode: '0644'
  tags:
    - setup

- name: Create network for proxying
  community.docker.docker_network:
    name: "{{ proxy_net }}"
    # enable_ipv6: yes
    driver_options:
      com.docker.network.bridge.name: "{{ proxy_net }}"
  become: yes
  tags:
    - setup

- name: Copy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "/home/{{ ansible_user }}/caddy/config/Caddyfile"
  become: yes
  tags:
    - setup

- name: Start caddy container
  community.docker.docker_container:
    image: "ghcr.io/hotio/caddy:release-2.4.3"
    name: "caddy"
    ports:
      - 80:80
      - "[::]:80:80"
      - 443:443
      - "[::]:443:443"
    volumes:
      - "/home/{{ ansible_user }}/caddy/data:/data"
      - "/home/{{ ansible_user }}/caddy/config:/config"
    env:
      XDG_CONFIG_HOME: /config
      XDG_DATA_HOME: /data
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ proxy_net }}"
    security_opts:
      - "label=disable"
    capabilities:
      - NET_ADMIN
  become: yes
  tags:
    - run
