---
# tasks for docker role

- name: Install docker and python3-docker
  ansible.builtin.package:
    name:
      - docker
      - python3-docker
    state: present
  become: yes

- name: Start and Enable docker service
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes
  become: yes
