# tasks that setup wallabag backups

- name: Create systemd user directories
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.config/systemd/user/
    state: directory
  tags:
    - setup

- name: Copy wallabag backup script, service and timer
  ansible.builtin.template:
    src: "{{ item.src }}.j2"
    dest: "/home/{{ ansible_user }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "wallabag-backup.sh", dest: "wallabag/wallabag-backup.sh", mode: "0744" }
    - { src: "wallabag-backup.service", dest: ".config/systemd/user/wallabag-backup.service", mode: "0644" }
    - { src: "wallabag-backup.timer", dest: ".config/systemd/user/wallabag-backup.timer", mode: "0644" }
  tags:
    - setup

- name: Ensure lingering enabled
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ ansible_user }}"
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"
  become: yes
  tags:
    - setup

- name: Start and Enable wallabag-backup timer
  ansible.builtin.systemd:
    name: wallabag-backup.timer
    state: started
    enabled: yes
    daemon_reload: yes
    scope: user
  tags:
    - setup
